### ISSUE TITLE
MRBrainS18 dataset

### ISSUE THREAD

**Issue by calvin89029** [hjkuijf/MRBrainS18#1]
Hi @hjkuijf 
I'm trying to download the MRBrainS18 dataset recently and I've sent my confidentiality agreement to mrbrains18@isi.uu.nl.
However, no reply is received and the website seems to be unavailable now.
It would be great if you can check it out for me.
Thank you so much.

**Comment by hjkuijf** [comment]
We process MRBrainS18 registration emails regularly. You have send your email one (1) business day ago. Please allow us some more time, since we also have other work to do.
